export type BaseTextContent = {
    LinkButtonText: string,
    SecurelySubmitPrompt: string,
    QBDesktop: string,
    QBOnline: string,
    Xero: string,
    ClickYourAccountingPackage: string,
    PNLStatements: string,
    BalanceSheets: string,
    TransactionData: string,
    NoteNoPersonalInformation: string,
    EstablishingSecureConnection: string,
    GatheringRequiredInformation: string,
    DeliveringToYourAccountMgr: string,
    YourDataIsSubmitted: string,
    Done: string,
    Continue: string,
    ConnectToAccountingPkg: string,
    DisconnectFromAccountingPkg: string,
    UnknownAccountingPkg: string,
    StartFinancialsCreateRequestDetailedError: string,
    StartFinancialsCreateRequestSummaryError: string,
    StartFinancialsCreateWindowDetailedError: string,
    StartFinancialsCreateWindowSummaryError: string,
    StartFinancialsImportDetailedError: string,
    StartFinancialsImportSummaryError: string,
    LinkModalDescriptionQBO: string,
    LinkModalDescriptionQBD: string,
    LinkModalDescriptionXero: string,
    LinkModalQBOneWay: string;
    LinkModalXeroOneWay: string;
    LinkModalWorking: string;
    LinkModalUpdateFinancialsNow: string;
    TermsDescriptionParagraph1PreSBX: string,
    TermsDescriptionParagraph1PostSBX: string,
    TermsDescriptionParagraph2: string,
    TermsDescriptionParagraph2Href: string,
    TermsBullet1Title: string;
    TermsBullet1Description: string;
    TermsBullet2Title: string;
    TermsBullet2Description: string;
}

